# Generated by Django 6.0.5 on 2026-05-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookMode',
            new_name='BookModel',
        ),
    ]
